sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
services:
  - rabbitmq
env:
  global:
    - BENCHMARK=True
    - DEBUGLOG=False
    - PIKALOG=False
  matrix:
    - DJANGO_VERSION="Django>=1.8,<1.9"
    - DJANGO_VERSION="Django>=1.9,<1.10"
    - DJANGO_VERSION="Django>=1.10,<1.11"
    - DJANGO_VERSION="Django>=1.11,<2.0"
    - DJANGO_VERSION="Django>=2.0,<2.1"
matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION="Django>=2.0,<2.1"
    - python: 3.6
      env: DJANGO_VERSION="Django>=1.8,<1.9"
    - python: 3.6
      env: DJANGO_VERSION="Django>=1.9,<1.10"
    - python: 3.6
      env: DJANGO_VERSION="Django>=1.10,<1.11"
cache:
  directories:
  - $HOME/.cache/pip/wheels
install:
  - pip install -U pip wheel setuptools
  - pip install -r requirements/qa.txt
  - pip install -r requirements/ci.txt
  - pip install $DJANGO_VERSION
  - pip install .[tests]
script:
  - pip freeze
  - coverage run -m pytest
after_success:
  - codecov
